"""empty message

Revision ID: 3cb59faf5ee5
Revises: 7252ce090b5f
Create Date: 2025-05-05 20:00:03.832748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cb59faf5ee5'
down_revision: Union[str, None] = '7252ce090b5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtasks', sa.Column('task_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'subtasks', 'tasks', ['task_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subtasks', type_='foreignkey')
    op.drop_column('subtasks', 'task_id')
    # ### end Alembic commands ###
