"""empty message

Revision ID: edd1473dd0ab
Revises: 
Create Date: 2025-04-30 19:33:22.332049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edd1473dd0ab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('finished_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('creator_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('finished_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('m2m_users_projects',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('finished_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_m2m_users_projects_id'), 'm2m_users_projects', ['id'], unique=False)
    op.create_index(op.f('ix_m2m_users_projects_project_id'), 'm2m_users_projects', ['project_id'], unique=False)
    op.create_index(op.f('ix_m2m_users_projects_user_id'), 'm2m_users_projects', ['user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('importance_status', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('creator_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('finished_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_table('m2m_users_tasks',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.Column('finished_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_m2m_users_tasks_id'), 'm2m_users_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_m2m_users_tasks_task_id'), 'm2m_users_tasks', ['task_id'], unique=False)
    op.create_index(op.f('ix_m2m_users_tasks_user_id'), 'm2m_users_tasks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_m2m_users_tasks_user_id'), table_name='m2m_users_tasks')
    op.drop_index(op.f('ix_m2m_users_tasks_task_id'), table_name='m2m_users_tasks')
    op.drop_index(op.f('ix_m2m_users_tasks_id'), table_name='m2m_users_tasks')
    op.drop_table('m2m_users_tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_m2m_users_projects_user_id'), table_name='m2m_users_projects')
    op.drop_index(op.f('ix_m2m_users_projects_project_id'), table_name='m2m_users_projects')
    op.drop_index(op.f('ix_m2m_users_projects_id'), table_name='m2m_users_projects')
    op.drop_table('m2m_users_projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
